### ISSUE TITLE
no module name google auth2

### ISSUE THREAD

**Issue by PareshParmar** [RhinoSecurityLabs/GCPBucketBrute#4]
Hi, 
i am getting this error while running
`python3 gcpbucketbrute.py -k test -u`

```
File "gcpbucketbrute.py", line 12, in <module>
    import google.oauth2.credentials
ModuleNotFoundError: No module named 'google.oauth2'
```

I've installed gsutil  and connected my account.  or i am missing something ?

Thanks

**Comment by SpenGietz** [comment]
Hmm you installed the `google-cloud-storage` package in requirements.txt too?

If that doesn't work, might be worth trying to install the GCP CLI. I'll make a note to look into this though and try to debug it myself. Let me know if you end up resolving it though!
