### ISSUE TITLE
How do i get credentials?

### ISSUE THREAD

**Issue by ankushgoel27** [RhinoSecurityLabs/GCPBucketBrute#7]
Hello,

I dont know how to get credentials to supply to the program. Can you please explain?

**Comment by philshem** [comment]
Did you read the readme?

> First, determine the type of authentication you want to use for enumeration between a user account, service account, or unauthenticated. If you are using a service account, provide the file path to the private key via the -f/--service-account-credential-file-path argument. If you are using a user account, don't provide an authentication argument. You will then be prompted to enter the access token of your user account for accessing the GCP APIs. If you want to scan completely unauthenticated, pass the -u/--unauthenticated argument to hide authentication prompts.

I'm not a contributor, but according to the code, if you don't provide a key file or access unauthenticated, a browser window will open and you will be prompted to authentication with a Google account via OAuth.
